# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[24,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://discord.gg/enginehub"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://worldedit.enginehub.org/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="worldedit-icon.png"
# A text field displayed in the mod UI
authors="EngineHub"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="worldedit-visualizer"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}"
 # A display name for the mod
displayName="WorldEdit Visualizer"
# The description text for the mod (multi line!)
description='''
WorldEdit Visualizer is a renderer for WorldEdit information, such as selections.
'''
[[dependencies.worldedit-visualizer]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion},${nextMajorMinecraftVersion})"
    ordering="NONE"
    side="BOTH"
[[dependencies.worldedit-visualizer]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeVersion},)"
    ordering="NONE"
    side="BOTH"
